project:
  type: website

website:
  title: "Subomi Omoleye"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: lifestyle.qmd
        text: lives


format:
  html:
    theme: minty
    css: styles.css
    toc: true



